# dbt_project.yml
name: weather_dbt_project
version: '1.0'
config-version: 2

# This should match the profile name in profiles.yml
profile: dbt_beginner_profile

# Where dbt will look for models
model-paths: ["models"]

# Where dbt will put compiled SQL and run artifacts
target-path: "target"

# Files/folders to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_modules"
